### ISSUE TITLE
News API functionality

### ISSUE THREAD

**Issue by kahaanpatel5** [SE-H-W/Project-02#10]
Add News API integration to fetch and display the latest news articles for the searched city. Ensure API key configuration in the .env file for secure access.

**Comment by AshwiniR1802** [comment]
Also make new page/redirect to new page for displaying news of the specific city

**Comment by Nirmit73** [comment]
News functionality added successfully
![Screenshot 2024-11-01 175508](https://github.com/user-attachments/assets/edf1a4ec-b050-4ce9-a44b-a585c414ef14)

**Comment by kahaanpatel5** [comment]
Seems nice!
