### ISSUE TITLE
Libraries deprecated

### ISSUE THREAD

**Issue by AshwiniR1802** [SE-H-W/Project-02#3]
The libraries are deprecated. We need to find libraries compatible with python 3.12 and need to update django to a higher level for using python 3.12

**Comment by Nirmit73** [comment]
This is a valid concern. It would be good to prioritize fixing this, and I’m available if you need a second set of eyes on the implementation or testing.

**Comment by kahaanpatel5** [comment]
There are multiple libraries deprecated and their versions need to be updated in requirements.txt. Also the new libraries integrated should be added in here.

**Comment by kahaanpatel5** [comment]
![image](https://github.com/user-attachments/assets/16c69592-3c87-4885-8166-775bf881f050)

The versions have been updated and new libraries have been added

**Comment by AshwiniR1802** [comment]
ok 👍
