### ISSUE TITLE
There is one more issue, in the signup page a user can sign up with the same email again, which should not be the case

### ISSUE THREAD

**Issue by AshwiniR1802** [SE-H-W/Project-02#4]

**Comment by Nirmit73** [comment]
Yes, this is serious security problem and needs to be fixed.

**Comment by kahaanpatel5** [comment]
Yes, we need to do a database lookup first.

**Comment by kahaanpatel5** [comment]
![image](https://github.com/user-attachments/assets/068171f0-4745-497c-af4e-52123242910d)

Added the code to do an email duplicate check first.

**Comment by AshwiniR1802** [comment]
ok ✅
