### ISSUE TITLE
Current UI Design is Lacking and Needs Attention

### ISSUE THREAD

**Issue by Nirmit73** [SE-H-W/Project-02#5]
The current design has several aspects that could be improved to enhance user experience, visual appeal, and overall functionality.

Concerns: 
- Clarity: Some elements of the UI are not intuitive, making it difficult for users to navigate through the application.
- Visual Design: The aesthetics of the UI feel outdated and could benefit from a modern design approach that aligns with current design trends.
- There are inconsistencies in fonts, colors, and button styles that disrupt the visual flow of the application.

**Comment by kahaanpatel5** [comment]
We can change the colors to more contrasting.

**Comment by kahaanpatel5** [comment]
And navbar also needs to be updated.

**Comment by AshwiniR1802** [comment]
ok I will try to make changes in the UI and will also improve the Navbar

**Comment by AshwiniR1802** [comment]
<img width="1695" alt="Screenshot 2024-11-01 at 10 37 15 PM" src="https://github.com/user-attachments/assets/3acebb7b-8292-4c15-a67a-f98f8ba1b45f">
<img width="1573" alt="Screenshot 2024-11-01 at 10 37 37 PM" src="https://github.com/user-attachments/assets/310ab4a0-0447-40be-968c-3d2882bc57b2">
<img width="981" alt="Screenshot 2024-11-01 at 10 37 54 PM" src="https://github.com/user-attachments/assets/af951423-6ad3-4912-98de-1594efb895dc">
Updated the UI for all the pages

**Comment by Nirmit73** [comment]
Nice UI, keep up the good work!
