### ISSUE TITLE
Lack of Navigation Options for Locations

### ISSUE THREAD

**Issue by Nirmit73** [SE-H-W/Project-02#6]
Currently, our project includes photos of various places, but it lacks an integrated map feature for easy navigation. Implementing a map integration would greatly enhance the user experience by allowing users to click on a photo and be directed to the corresponding geographical location on Google Maps.

**Comment by AshwiniR1802** [comment]
working on it

**Comment by AshwiniR1802** [comment]
<img width="966" alt="image" src="https://github.com/user-attachments/assets/4897d254-66c9-4644-99ea-f11e0f64cb9d">
<img width="309" alt="Screenshot 2024-11-01 at 10 05 31 PM" src="https://github.com/user-attachments/assets/65a3fb04-e002-4ed9-b165-3bbb684158eb">
Updated the code for maps

**Comment by Nirmit73** [comment]
Great work!
