### ISSUE TITLE
Missing Itinerary Feature for Trip Planning

### ISSUE THREAD

**Issue by Nirmit73** [SE-H-W/Project-02#7]
Currently, our application does not provide users with the ability to generate an itinerary based on the number of days they plan to visit a location. This functionality is crucial for enhancing the user experience by allowing users to plan their visits effectively and make the most of their time at various destinations.

**Comment by AshwiniR1802** [comment]
<img width="955" alt="Screenshot 2024-11-01 at 10 02 32 PM" src="https://github.com/user-attachments/assets/5435333f-7924-45f4-84cc-b4fe7d4269b2">
<img width="1210" alt="Screenshot 2024-11-01 at 10 03 00 PM" src="https://github.com/user-attachments/assets/e64730ac-6bd8-4c0e-bcfe-1eb573b258a2">

Added the functionality of itinerary

**Comment by Nirmit73** [comment]
Good job!
