### ISSUE TITLE
Forgot Password Functionality

### ISSUE THREAD

**Issue by kahaanpatel5** [SE-H-W/Project-02#8]
Implement a "Forgot Password" feature on the login page to allow users to reset their password if they've forgotten it.

**Comment by AshwiniR1802** [comment]
As there is field for Username we also need to add Email, for sending the forgot password link

**Comment by Nirmit73** [comment]
Thanks for raising this issue! I agree that adding a 'Forgot Password' feature would be highly valuable for our users. I’ll start working on implementing a secure password reset workflow, which will include sending a password reset link to the user's registered email.

**Comment by Nirmit73** [comment]
Forgot Password functionality has been added successfully
![Screenshot 2024-11-01 230925](https://github.com/user-attachments/assets/95241206-2482-491e-b5de-6808b3743cc9)
![Screenshot 2024-11-01 230940](https://github.com/user-attachments/assets/106069a5-f470-4b91-8a57-8fa5c94ff609)

**Comment by kahaanpatel5** [comment]
Looks good now!
