### ISSUE TITLE
Update API info in .env file

### ISSUE THREAD

**Issue by kahaanpatel5** [SE-H-W/Project-02#9]
Update the .env file to include the correct API key and URL to ensure API functionality is properly configured.

**Comment by AshwiniR1802** [comment]
There is no API for gemini in .env. As we have added it in the .py file, therefore we need to remove from there and add it into the .env

**Comment by Nirmit73** [comment]
The env files are updated

**Comment by kahaanpatel5** [comment]
Great work!
